# .streamlit/secrets.toml
# Add these in Streamlit Cloud under App Settings > Secrets

STRAVA_CLIENT_ID = "171563"
STRAVA_CLIENT_SECRET = "61d6da8af3fe3273ed909dadaee7af693a8bd1df"
REDIRECT_URI = "https://marathonplanner.streamlit.app"
